<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Login Suite" duration-ms="32" started-at="2016-03-07T17:16:35Z" finished-at="2016-03-07T17:16:35Z">
    <groups>
    </groups>
    <test name="ValidLoginTest" duration-ms="32" started-at="2016-03-07T17:16:35Z" finished-at="2016-03-07T17:16:35Z">
      <class name="com.testnowjavasample.Login.ValidLoginTest">
        <test-method status="PASS" signature="checkSuiteSkip()[pri:0, instance:com.testnowjavasample.Login.ValidLoginTest@36d64342]" name="checkSuiteSkip" is-config="true" duration-ms="937" started-at="2016-03-07T22:46:35Z" finished-at="2016-03-07T22:46:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkSuiteSkip -->
        <test-method status="PASS" signature="checkTestSkip()[pri:0, instance:com.testnowjavasample.Login.ValidLoginTest@36d64342]" name="checkTestSkip" is-config="true" duration-ms="3" started-at="2016-03-07T22:46:35Z" finished-at="2016-03-07T22:46:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkTestSkip -->
        <test-method status="FAIL" signature="ValidTestData(java.lang.String, java.lang.String)[pri:0, instance:com.testnowjavasample.Login.ValidLoginTest@36d64342]" name="ValidTestData" duration-ms="11" started-at="2016-03-07T22:46:35Z" data-provider="getTestData" finished-at="2016-03-07T22:46:35Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
The data provider is trying to pass 4 parameters but the method com.testnowjavasample.Login.ValidLoginTest#ValidTestData takes 2]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
The data provider is trying to pass 4 parameters but the method com.testnowjavasample.Login.ValidLoginTest#ValidTestData takes 2
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1229)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1122)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1240)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidTestData -->
      </class> <!-- com.testnowjavasample.Login.ValidLoginTest -->
    </test> <!-- ValidLoginTest -->
  </suite> <!-- Login Suite -->
  <suite name="TestNow Suites" duration-ms="0" started-at="2016-03-07T17:16:36Z" finished-at="2016-03-07T17:16:36Z">
    <groups>
    </groups>
  </suite> <!-- TestNow Suites -->
</testng-results>
